### ISSUE TITLE
Error on quick info appointment in Department row.

### ISSUE THREAD

**Issue by dachieu1996** [syncfusion/ej2-showcase-angular-appointment-planner#4]
![image](https://user-images.githubusercontent.com/33906137/115148221-cf5e6b00-a088-11eb-99af-0c6bcb508a1b.png)

Move one appointment to Department row at Timeline Day view. And click to see quick info, you will get the error.

**Comment by Nevitha-Ravi** [comment]
Hi @dachieu1996 ,

The issue has been resolved now. Can you please check and revert us back?

Regards,
Nevitha
