### ISSUE TITLE
What backend is it using?

### ISSUE THREAD

**Issue by ugintl** [syncfusion/ej2-showcase-angular-appointment-planner#7]
If it is using a database, then how to change the db details?

**Comment by Nevitha-Ravi** [comment]
Hi @ugintl ,

We can update data to the database when performing CRUD action using DataManager and Adaptors like ODataV4, URLAdaptor , CustomAdaptor. Please refer to the following UG for the same.
https://ej2.syncfusion.com/angular/documentation/schedule/data-binding/#binding-remote-data 

Please let us know if you have any queries.

Regards,
Nevitha

**Comment by ugintl** [comment]
I visited the link, but I did not understand anything. I thought there would be something like config file where I can put my database details. I am familiar with php mysql apps.

**Comment by Nevitha-Ravi** [comment]
Hi @ugintl ,

You can use PHP as backend to fetch appointments from database and update the changes to database on CRUD actions. Please refer to the following forum for the same.
https://www.syncfusion.com/forums/153232/example-of-crud-operation-on-ej-schedule-2-in-php 

Regards,
Nevitha
